version: "3.9"

services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

  backend:
    build: ./backend
    restart: unless-stopped
    env_file: .env
    depends_on:
      - db
      - minio
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    restart: unless-stopped
    environment:
      # Folosim path relativ ca sa treaca prin Nginx
      VITE_API_BASE: /api
    ports:
      - "5173:5173"

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    volumes:
      - ./infra/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - frontend
    ports:
      - "80:80"

volumes:
  db_data:
  minio_data:
